apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jagadishkl/platform-infra.git
    targetRevision: HEAD
    path: argocd-apps/base/monitoring
  destination:
    server: https://192.168.56.20:6443
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

