apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-infra-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR-ORG/platform-infra.git
    path: argocd-apps
    directory:
      recurse: true
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

