apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jagadishkl/platform-infra.git
    path: base/ingress
    targetRevision: HEAD
  destination:
    server: https://192.168.56.20:6443
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

